name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install minimal stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: target
        # An explicit key for restoring and saving the cache
        key: cargo-${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-${{ runner.os }}-build-
          cargo-${{ runner.os }}-
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
